// import Head from "next/head";

import Services from "../components/Services";

import { getClient, overlayDrafts } from "../lib/sanity.server";
import { indexQuery } from "../lib/queries";
import Layout from "../components/Layout";
import Panel from "../components/Panel";

export default function Index({ services, preview }: any) {
  return (
    <Layout preview={preview}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Panel />
      <Services services={services} />
    </Layout>
  );
}

export async function getStaticProps({ preview = false }) {
  const services = overlayDrafts(await getClient(preview).fetch(indexQuery));
  return {
    props: { services, preview },
  };
}
